[workspace]
members = [
  "./day1",
  "./day2",
  "./day3",
  "./day4",
  "./day5",
  "./day6"
]
resolver = "2"

[workspace.dependencies]
glam = "0.29.2"
nom = "7.1.3"
itertools = "0.13.0"

[profile.release]
debug = true
