[package]
name = "day7"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "part1"
test = true

[[bin]]
name = "part2"
test = true

[dependencies]
itertools.workspace = true
nom = { workspace = true }
